apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-vol
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql"
  persistentVolumeReclaimPolicy: Retain
