apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-nfs-vol
spec:
  capacity:
    storage: 49Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/www/html"
  persistentVolumeReclaimPolicy: Retain
